### ISSUE TITLE
Add option to open in Remote-SSH

### ISSUE THREAD

**Issue by fiveisprime** [microsoft/vscode-azurevirtualmachines#105]

**Comment by bamurtaugh** [comment]
To specify the idea a little bit more, the option to open with Remote-SSH would come up when users right-click on a VM:

![image](https://user-images.githubusercontent.com/25310137/95130584-ab9d8e00-0711-11eb-8ce9-c90268671360.png)

It could be like the Remote-Containers command we add to the Docker extension with "Attach Visual Studio Code:" 
![image](https://user-images.githubusercontent.com/25310137/95130619-b821e680-0711-11eb-92b5-8ff28e4de6b0.png)

And/or look something like the right-click menu for SSH targets in the Remote Explorer:
![image](https://user-images.githubusercontent.com/25310137/95130649-c112b800-0711-11eb-94e2-7e8c4dc1c8f2.png)

**Comment by nturinski** [comment]
Yeah, unfortunately today the only thing we can do is open this prompt for the users because we can't pass any parameters to Remote-SSH: Connect to Host command: 
![image](https://user-images.githubusercontent.com/5290572/95240075-bd8a3a00-07c0-11eb-876c-e110bd6d0b0e.png)

**Comment by bamurtaugh** [comment]
Hey @nturinski just to double-check, since the linked Remote-SSH issue has been addressed, is this on the team's backlog for 0.3.0? Is there any projected timeline?

**Comment by nturinski** [comment]
Hi @bamurtaugh Yeah, this is definitely in the 0.3.0 milestone.  As far as release date, we haven't decided anything yet, but I'll definitely be working on this feature this month.

**Comment by bamurtaugh** [comment]
Thanks for the update @nturinski!

**Comment by nturinski** [comment]
Hi @bamurtaugh 

Just wanted to let you know that the v0.3.0 released today and now includes this feature!

**Comment by bamurtaugh** [comment]
Thanks for the update @nturinski! I just tried it out and was able to successfully connect 😄.

I did have a question - I was hoping you'd be able to help me understand the flow a bit better here: 

![recording (2)](https://user-images.githubusercontent.com/25310137/107295522-602f1f80-6a24-11eb-9447-25f1d53a35c4.gif)

I figured it was unable to find my host because it was my first time connecting to it, so I connected to this VM in an external terminal (although that felt unnecessary). However, I was still receiving the same message when I returned to VS Code. 

I was also confused why the prompt brought me to my public key file rather than the `known_hosts` or `config` file based on the wording `Add new SSH config host`.

In the end, clicking on the .pub file did lead to a successful connection, though, and future reconnections worked well.

Perhaps I'm misunderstanding the wording/how this flow is intended to work/missing another file?
