### ISSUE TITLE
Can't install VM extension to remote machine

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurevirtualmachines#118]
**OS:** Mac
**Build Version:** 20200616.3

**Repro Step:**

1. Create a virtual machine.
2. Uninstall VM extension.
3. Connect to VM via Remote SSH.
4. F1 --> Install from VSIX --> Select "Show Local" --> Select the .vsix file of VM extension.

**Expect:**
Install VM extension to remote machine.

**Actual:**
Install VM extension to local machine.

**More info:**

1. Succeed to install Docker extension to remote machine.
2. This issue was not verified on Win/Linux, because the connection failed on Win/Linux.

**Comment by nturinski** [comment]
Hi @v-mengwe

This is actually expected behavior.  We've changed the extension to default to the be a UI extension.  If you want to install the extension on a remote machine, you'll have to change the VS Code settings to run as a workspace extension.

You can do that with the following VS Code settings:
```
{
  "remote.extensionKind": {
    "ms-azuretools.vscode-cosmosdb": ["ui"],
    "ms-azuretools.vscode-azurevirtualmachines": ["workspace"]
  }
}
```
