### ISSUE TITLE
Fail to connect a Windows VM with "timed out" error

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurevirtualmachines#181]
**OS:** Mac
**Build Version:** 20201207.1

**Repro Steps:**
1. Make sure the Remote - SSH Extension has been installed.
2. Create a Windows VM.
3. Navigate to the Remote Explorer --> Refresh the Remote Explorer --> Right click the new Windows VM host --> Select "Connect to Host in New Window".

**Expect:**
Succeed to connect the Windows VM.

**Actual:**
Fail to connect the Windows VM with "time out" error.
![Screen Shot 2020-12-08 at 5 58 45 PM](https://user-images.githubusercontent.com/45614674/101469650-f9d44500-397f-11eb-86f9-bf9293621b8b.png)

**More Info:**
This issue does not reproduce when connecting a Linux VM on Mac platform.

**Comment by nturinski** [comment]
@v-ruizh This would be a VS Code bug since we aren't the ones who manage the Remote - SSH Extension.  However, Windows VMs do _not_ use SSH to connect remotely.  I think typically you would use RDP (remote desktop protocol) to connect to a Windows VM which is most likely why this didn't work.  I'm pretty sure that this isn't a bug-- the Remote - SSH Extension just doesn't have a way to know tell if the host you're trying to connect to is Linux or Windows.
