### ISSUE TITLE
Creation failed with error that size isn't available in region

### ISSUE THREAD

**Issue by fiveisprime** [microsoft/vscode-azurevirtualmachines#20]
Seems odd that the default size doesn't work in West US. Is this a fluke?

Action: azureVirtualMachines.createVirtualMachine
Error type: SkuNotAvailable
Error Message: The requested size for resource '/subscriptions/546ac631-883f-4fb4-bff0-b8639ed6e7c8/resourceGroups/maherna/providers/Microsoft.Compute/virtualMachines/maherna-testbox' is currently not available in location 'westus' zones '' for subscription '546ac631-883f-4fb4-bff0-b8639ed6e7c8'. Please try another size or deploy to a different location or zones. See https://aka.ms/azureskunotavailable for details.

Version: 0.1.0-alpha
OS: linux
OS Release: 4.19.84-microsoft-standard
Product: Visual Studio Code
Product Version: 1.42.1
Language: en

```
extension.bundle.js:218:1015639
s extension.bundle.js:218:110805
s extension.bundle.js:134:25108
extension.bundle.js:134:26348
o extension.bundle.js:134:388917
extension.bundle.js:134:24029
$._callback extension.bundle.js:8:1123
$.t._callback.t.callback.t.callback extension.bundle.js:194:5523
$.emit events.js:200:13
$.<anonymous> extension.bundle.js:194:18336
$.emit events.js:205:15
IncomingMessage.<anonymous> extension.bundle.js:194:17178
Object.onceWrapper events.js:288:20
IncomingMessage.emit events.js:205:15
endReadableNT _stream_readable.js:1154:12
processTicksAndRejections task_queues.js:84:9
```

</details>

**Comment by fiveisprime** [comment]
Was thinking that I saw this because I chose an older, existing RG.. but I tried with a new RG and got the same error.

Should definitely be able to create the default size in West US (and all regions). I'm hoping this is just a capacity error. 🤷‍♀️

**Comment by v-dantch** [comment]
Hi @fiveisprime , we verified this issue just now on Windows. We are not sure if it is related to platform, and the new VM with west us region can be created successfully. 
Meanwhile we create this VM by the "Create Virtual Machine..." option and we are also not sure whether the size is the default size you mentioned. 
![image](https://user-images.githubusercontent.com/34729092/75014894-3d36e480-543c-11ea-8c99-8f0e34195614.png)

**Comment by fiveisprime** [comment]
I'm still seeing this. On Windows in Stable VS Code built from master

**Comment by nturinski** [comment]
Are you able to create a VM with these specs through the portal?

**Comment by nturinski** [comment]
Wondering if there's a storage of VMs or something.  In the Portal, I'm seeing a number of regions that are just completely restricted including the default that is selected, Central US.

![image](https://user-images.githubusercontent.com/5290572/91102984-31142580-e61f-11ea-8153-cc0446eb6949.png)

Happens for West US as well.  I'm wondering if it's because I'm an internal user?

**Comment by nturinski** [comment]
This should have been fixed by https://github.com/microsoft/vscode-azurevirtualmachines/pull/256/files & https://github.com/microsoft/vscode-azurevirtualmachines/pull/262

As you can see, the location West US doesn't appear on the list anymore: 
![image](https://user-images.githubusercontent.com/5290572/125341293-52016a00-e308-11eb-8a6d-9e88edf1a053.png)

While US West and some other locations such as UAE North show up in the portal, our logic filters them out now.
