### ISSUE TITLE
Remove resource group from label

### ISSUE THREAD

**Issue by EricJizbaMSFT** [microsoft/vscode-azurevirtualmachines#39]
Might just be my opinion - but I think it looks real ugly to have resource group in the label. I understand there could be duplicates - a few ideas related to that:
1. Detect if there's duplicates and only show resource group for those tree items
1. Show resource group as a part of "description" instead of the first part of the label (since the vm name is more important and might not be shown if there's not enough real estate on the screen)
1. Say "who cares" to people that name their VMs the same thing 😂👀🤷‍♂️

**Comment by EricJizbaMSFT** [comment]
Part of why it looks so ugly to me is that the default rg name and vm name are always the same in our wizard:
![Screen Shot 2020-02-24 at 2 07 56 PM](https://user-images.githubusercontent.com/11282622/75195614-1c59e200-570f-11ea-9f2d-2bc483a6ed18.png)

**Comment by nturinski** [comment]
I'm opting for 3.

1 is definitely possible, but finding out which labels are duplicates before creating the tree item feels like more trouble than its worth tbh.
2 doesn't seem ideal since we use that to display the VM's current state.

To mitigate not seeing the RG, I'm going to add the view property context menu item.  So if users do have duplicate names, they can at least check from there.
